# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='userHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=25)),
                ('url', models.URLField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.UserDetails')),
            ],
        ),
    ]
