# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20171018_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
