# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('item_type', models.TextField()),
                ('item_location', models.TextField()),
                ('item_exprice', models.TextField()),
                ('item_usetime', models.TextField()),
                ('item_reason', models.TextField()),
                ('item_pic', models.ImageField(blank=True, upload_to='useritems')),
            ],
        ),
    ]
