# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('item_name', models.CharField(max_length=25)),
                ('item_type', models.CharField(max_length=15)),
                ('item_location', models.TextField()),
                ('item_exprice', models.CharField(max_length=50)),
                ('item_usetime', models.CharField(max_length=15)),
                ('item_reason', models.TextField()),
                ('item_pic', models.ImageField(blank=True, upload_to='useritems')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
