# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selliteminfo',
            name='item_exprice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='selliteminfo',
            name='item_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='selliteminfo',
            name='item_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='selliteminfo',
            name='item_usetime',
            field=models.CharField(max_length=15),
        ),
    ]
