# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profilepic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.UserProfileInfo'),
            preserve_default=False,
        ),
    ]
