# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
