# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_notification_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='profilepic',
        ),
        migrations.AlterField(
            model_name='notification',
            name='to',
            field=models.CharField(max_length=20),
        ),
    ]
