# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='fromm',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
