# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_notification_fromm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='fromm',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='to',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
