# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_selliteminfo_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='selliteminfo',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
